version: 2.1

jobs:
  unit:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt --use-feature=2020-resolver
            pytest tests/unit --mypy --flake8 -vvvvv --ignore=src

  integrate:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt --use-feature=2020-resolver
            cp ./resources/all_paths/traverser.py ./traverser.py
            cp ./resources/all_paths/common_args.py ./common_args.py
            pytest tests/integrate -vvvvv
            rm -f ./traverser.py ./common_args.py

workflows:
  build_and_test:
    jobs:
      - unit
      - integrate
