version: 2.1

jobs:
  unit:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt --use-feature=2020-resolver
            pytest --mypy --flake8

workflows:
  build_and_test:
    jobs:
      - unit
