version: 2.1

jobs:
  unit:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: time ./resources/icecube_combo.sh && pip install -r requirements.txt && pytest tests

workflows:
  build_and_test:
    jobs:
      - unit
