version: 2.1

jobs:
  unit:
    docker:
      - image: icecube/icetray:latest
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: /usr/local/icetray/env-shell.sh && pip install -r requirements.txt && pytest tests

workflows:
  build_and_test:
    jobs:
      - unit
