version: 2.1

jobs:
  unit:
    docker:
      - image: icecube/icetray:latest
    steps:
      - checkout
      - run: pip3 install -r requirements.txt && pytest tests

workflows:
  build_and_test:
    jobs:
      - unit
