version: 2.1

jobs:

  unit:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: |
          pip install --user tox
          tox tests/unit -vv

  integration:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: |
          pip install --user tox
          tox tests/integration -vv

workflows:
  build_and_test:
    jobs:
      - unit
      - integration
