version: 2.1

jobs:
  unit:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install -r requirements.txt && pytest

workflows:
  build_and_test:
    jobs:
      - unit
