version: 2.1

jobs:
  unit:
    docker:
      - image: icecube/icetray:combo-stable-devel
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get install -y git-all
            sudo apt-get install -y python3-pip
            python3 -m pip install -r requirements.txt
            pytest tests

workflows:
  build_and_test:
    jobs:
      - unit
